// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpgtzebpzbkcjtuffluo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwZ3R6ZWJwemJrY2p0dWZmbHVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3ODMwMzIsImV4cCI6MjA4MzM1OTAzMn0.K4RuWsbFMXyvnMn8M1O3j16tz_rkYCZZUBt5bWyrFWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});